import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :photo_site, PhotoSiteWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PhotoSite.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Ecto
config :photo_site, PhotoSite.Repo,
  username: System.get_env(""),
  password: System.get_env(""),
  hostname: System.get_env(""),
  database: System.get_env("")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
